CREATE TABLE  "DEPARTMENTS" 
   (	"DEPARTMENT_ID" NUMBER(5,0) NOT NULL ENABLE, 
	"DEPARTMENT_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "DEPARTMENTS_PK" PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX  ENABLE
   )
/