SELECT 
(SELECT DEPARTMENT_NAME FROM DEPARTMENTS C WHERE C.DEPARTMENT_ID = A.DEPARTMENT_ID) AS DEPARTMENT_NAME,
SUM(B.SALARY) AS SALARY_SUM
FROM DEPARTMENTS A, EMPLOYEES B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
GROUP BY A.DEPARTMENT_ID
ORDER BY A.DEPARTMENT_ID
/