DELETE FROM DEPARTMENTS;

INSERT INTO DEPARTMENTS
(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION)
VALUES(1,'Management','London');

INSERT INTO DEPARTMENTS
(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION)
VALUES(2,'Engineering','Cardif');

INSERT INTO DEPARTMENTS
(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION)
VALUES(3,'Research & Development','Edinburgh');

INSERT INTO DEPARTMENTS
(DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION)
VALUES(4,'Sales','Belfast');